FO-2900: La lenke til beslutteroversikt
navikt/internarbeidsflatedecorator pull request #125
Opened 2020-05-14 11:58 UTC by sneha-d-desai

2020-05-14 12:05 UTC, AlexGaard requested changes
Kan ikke se noen feature-toggle, er det lagt til?

2020-05-19 09:23 UTC, janeirik commented
Når er denne tenkt at skal leveres?

2020-05-20 08:40 UTC, AlexGaard commented
Vi venter litt til med denne PRen. Vi legger en feature toggle på beslutteroversikten som viser en prelanseringsside til de som ikke har tilgang. Men vi kan ikke merge inn denne PRen før prelanseringssiden er på plass.

2020-06-04 11:31 UTC, nutgaard approved these changes

2020-06-15 08:56 UTC, AlexGaard approved these changes

2020-06-15 09:16 UTC, nutgaard commented
@sneha-d-desai @AlexGaard Sånn å forstå at dere vil ha denne ut nå?

2020-06-16 08:58 UTC, merged