[PROD][OPP-1511] Forbedringer internarbeidsflatedecorator
navikt/internarbeidsflatedecorator pull request #354
Opened 2022-11-29 11:04 UTC by abrhanav

2022-11-29 12:12 UTC, nutgaard requested changes
Noe funky har skjedd med npm/package.json her tror jeg

![image](https://user-images.githubusercontent.com/1413417/204525886-0bb89333-327d-4f10-bd82-de7b83069580.png)

2022-12-02 08:13 UTC, nutgaard commented on src/components/hurtigtaster/hurtigtast-modal.tsx
> +import './hurtigtaster.css';
[NITPICK] trenger ikke denne da `hurtigtast-meny-element.tsx` allerede importerer denne

2022-12-02 08:50 UTC, nutgaard approved these changes

2022-12-02 08:50 UTC, nutgaard commented on src/components/hurtigtaster/hurtigtast-modal.tsx
> +import './hurtigtaster.css';
Men ser stylingen ikke blir duplisert, så har fint lite å si ;)

2022-12-02 12:15 UTC, Jesperpaulsen approved these changes
<img src="https://media4.giphy.com/media/XjlNyeZp5lDri/giphy-downsized-medium.gif"/>

2022-12-02 12:23 UTC, merged