PFP-1762 rettet Lenke til FPSAK
navikt/internarbeidsflatedecorator pull request #8
Opened 2019-02-22 17:33 UTC by mijohansen

https://jira.adeo.no/browse/PFP-1762

Liten feil på lenken til fpsak.

2019-02-25 07:15 UTC, ketilsan commented on js/menyConfig.js
> +        url: (aktorId && aktorId.data && aktorId.length > 0 ? `${appDomain}/fpsak/aktoer/${aktorId.data}` : `${appDomain}/fpsak/`),
ser du har lagt på trailing slash i lenken uten aktørId, dette er bevisst?

2019-02-25 07:16 UTC, ketilsan commented
Dette vil ikke fungere før aktorSaga() er lagt til på nytt og importert i sagas/index.html

2019-02-25 07:17 UTC, ketilsan requested changes
Se kommentarer.

2019-02-25 07:21 UTC, mijohansen commented
Har lagt inn rettede urler. Fpsak har trailing slashes, så derfor la jeg på det. Skal fungere slik som den har gjort før uten saga.

2019-02-25 07:55 UTC, ketilsan commented
ok! Men så du min andre kommentar? Jeg har kommentert ut oppsett av aktoerSaga også, dette må på plass igjen for at aktør-kallet faktisk skal bli gjort.

2019-02-25 10:23 UTC, mijohansen commented
@ketilsan om dere velger å skru på aktørid, så vil vel det der fungere som det skal. Jeg bare rettet lenken som var feil. :-)

2019-02-26 07:22 UTC, ketilsan approved these changes

2019-02-26 07:22 UTC, merged